services:
  # PostgreSQL service
  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Map PostgreSQL port to host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage

# Define a volume for PostgreSQL
volumes:
  postgres_data: